CREATE TABLE IF NOT EXISTS vendas (
  id VARCHAR(36) NOT NULL,
  usuario_id VARCHAR(36) NOT NULL,
  estoque_id VARCHAR(36) NOT NULL,
  produto_id VARCHAR(36) DEFAULT NULL,
  produto_nome VARCHAR(255) NOT NULL,
  categoria_nome VARCHAR(100) DEFAULT NULL,
  canal_venda_id VARCHAR(36) DEFAULT NULL,
  canal_nome VARCHAR(100) DEFAULT NULL,
  preco_custo DECIMAL(10,2) DEFAULT NULL,
  valor_bruto DECIMAL(10,2) DEFAULT NULL,
  taxa_plataforma DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  frete_vendedor DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  valor_liquido DECIMAL(10,2) DEFAULT NULL,
  data_venda DATETIME DEFAULT NULL,
  status ENUM('concluida','cancelada') NOT NULL DEFAULT 'concluida',
  cancelada_em DATETIME DEFAULT NULL,
  criado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  atualizado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_vendas_usuario_data (usuario_id, data_venda),
  KEY idx_vendas_usuario_status (usuario_id, status),
  KEY idx_vendas_estoque (estoque_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
