import React, { useState } from 'react';
import { Download, FileDown, FileUp, ShieldCheck } from 'lucide-react';
import { useData } from '../contexts/DataContext';
import { useToast } from '../components/Toast';

const INPUT_TEMPLATE = '\uFEFFnome;marca;categoria;tipo;quantidade;custo unitário;origem\n';
const saveBlob = (blob, filename) => { const link = document.createElement('a'); const url = URL.createObjectURL(blob); link.href = url; link.download = filename; document.body.appendChild(link); link.click(); link.remove(); URL.revokeObjectURL(url); };
const parseCsv = (text) => {
    const source = text.replace(/^\uFEFF/, ''); const separator = (source.split(/\r?\n/, 1)[0] || '').includes(';') ? ';' : ','; const rows = []; let row = []; let value = ''; let quoted = false;
    for (let index = 0; index < source.length; index += 1) { const char = source[index]; if (char === '"') { if (quoted && source[index + 1] === '"') { value += '"'; index += 1; } else quoted = !quoted; } else if (char === separator && !quoted) { row.push(value); value = ''; } else if ((char === '\n' || char === '\r') && !quoted) { if (char === '\r' && source[index + 1] === '\n') index += 1; row.push(value); if (row.some((cell) => cell.trim())) rows.push(row); row = []; value = ''; } else value += char; }
    row.push(value); if (row.some((cell) => cell.trim())) rows.push(row); if (!rows.length || quoted) throw new Error('CSV vazio ou com aspas não finalizadas.'); const headers = rows[0].map((header) => header.trim().toLocaleLowerCase('pt-BR')); return rows.slice(1).map((cells) => Object.fromEntries(cells.map((cell, index) => [headers[index], cell.trim()])));
};

const Portabilidade = () => {
    const { fetchData } = useData(); const toast = useToast(); const [rows, setRows] = useState([]); const [fileName, setFileName] = useState(''); const [importing, setImporting] = useState(false); const api = `${import.meta.env.VITE_API_URL || 'http://localhost:3001'}/api/portabilidade`;
    const download = async (path, filename) => { try { const response = await fetch(`${api}${path}`, { credentials: 'include' }); if (!response.ok) throw new Error(); saveBlob(await response.blob(), filename); } catch { toast.error('Erro ao exportar', 'Tente novamente.'); } };
    const downloadTemplate = () => saveBlob(new Blob([INPUT_TEMPLATE], { type: 'text/csv;charset=utf-8' }), 'modelo-entrada-estoque.csv');
    const selectFile = async (event) => { const file = event.target.files?.[0]; if (!file) return; try { const parsed = parseCsv(await file.text()); const normalized = parsed.map((row) => ({ nome: row.nome || row.produto || '', marca: row.marca || '', categoria: row.categoria || '', tipo: row.tipo || '', quantidade: row.quantidade || '1', custoUnitario: row['custo unitário'] || row['custo unitario'] || row.custounitario || row.custo || '', origem: row.origem || 'nacional' })); if (!normalized.length) throw new Error('O CSV não possui linhas de dados.'); setRows(normalized); setFileName(file.name); } catch (error) { setRows([]); setFileName(''); toast.error('CSV inválido', error.message || 'Não foi possível ler o arquivo.'); } finally { event.target.value = ''; } };
    const importRows = async () => { setImporting(true); try { const response = await fetch(`${api}/importar/estoque`, { method: 'POST', credentials: 'include', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ rows }) }); const data = await response.json(); if (!response.ok) return toast.error('Importação não concluída', data.errors?.[0]?.mensagem || data.message); toast.success('Importação concluída', `${data.itensAdicionados} itens foram adicionados.`); setRows([]); setFileName(''); await fetchData(); } catch { toast.error('Erro de conexão', 'Não foi possível importar o arquivo.'); } finally { setImporting(false); } };
    return <div className="container max-w-5xl"><div className="page-header"><div><h1 className="page-title">Dados e backup</h1><p className="page-subtitle">Seus dados continuam portáteis: exporte, guarde e importe com prévia.</p></div></div><div className="grid md:grid-cols-3 gap-4 mb-7">{[['/estoque.csv', 'revendasmart-estoque.csv', 'Exportar estoque', 'Baixe as unidades registradas em CSV.'], ['/vendas.csv', 'revendasmart-vendas.csv', 'Exportar vendas', 'Baixe o histórico de vendas em CSV.'], ['/backup.zip', 'revendasmart-backup-completo.zip', 'Backup completo (ZIP)', 'CSVs organizados para abrir no Excel.']].map(([path, filename, label, description]) => <button key={path} onClick={() => download(path, filename)} className="card text-left hover:border-blue-400 transition-colors"><Download className="text-blue-500 mb-4" /><p className="font-bold">{label}</p><p className="text-sm text-slate-500 mt-1">{description}</p></button>)}</div><div className="card"><div className="flex gap-3 items-start"><div className="p-3 rounded-xl bg-violet-100 dark:bg-violet-900/30"><FileUp className="text-violet-600" /></div><div><h2 className="section-heading">Importar entradas por CSV</h2><p className="text-sm text-slate-500 mt-1">Cabeçalhos aceitos: nome, marca, categoria, tipo, quantidade, custo unitário e origem. A importação só ocorre após sua confirmação.</p></div></div><div className="mt-5 flex flex-wrap gap-3"><label className="btn btn-secondary inline-flex"><FileUp size={17} />Escolher CSV<input className="hidden" type="file" accept=".csv,text/csv" onChange={selectFile} /></label><button type="button" className="btn btn-secondary" onClick={downloadTemplate}><FileDown size={17} />Baixar modelo CSV</button></div>{rows.length > 0 && <div className="mt-6"><div className="flex justify-between items-center mb-3"><p className="font-semibold">Prévia: {fileName} · {rows.length} linha(s)</p><button disabled={importing} className="btn btn-primary" onClick={importRows}>{importing ? 'Importando...' : 'Confirmar importação'}</button></div><div className="table-container border rounded-xl"><table><thead><tr><th>Produto</th><th>Qtd.</th><th>Custo</th><th>Origem</th></tr></thead><tbody>{rows.slice(0, 20).map((row, index) => <tr key={index}><td>{row.nome}</td><td>{row.quantidade}</td><td>{row.custoUnitario}</td><td>{row.origem}</td></tr>)}</tbody></table></div>{rows.length > 20 && <p className="text-xs text-slate-500 mt-2">Mostrando as primeiras 20 linhas.</p>}</div>}</div><div className="mt-5 flex gap-3 text-sm text-slate-500"><ShieldCheck className="text-green-500 shrink-0" /><p>O backup ZIP contém arquivos CSV separados por tipo de dado, prontos para consulta no Excel. Para restaurar um backup, use primeiro uma base de teste.</p></div></div>;
};
export default Portabilidade;
